apiVersion: v1
kind: Service
metadata:
  name: otel-agent-metrics
  namespace: otel-agent
  labels:
    app.kubernetes.io/name: opentelemetry-collector
spec:
  selector:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: otel-agent
  ports:
    - name: prometheus-metrics
      port: 8888
      targetPort: 8888
      protocol: TCP


