
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-agent-opentelemetry-collector
  namespace: otel-agent
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: opamp-fleet


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-agent-kubeletstats-role
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: opamp-fleet
rules:

  - apiGroups: [""]
    resources: ["nodes/stats"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-agent-kubeletstats-binding
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: opamp-fleet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-agent-kubeletstats-role
subjects:
  - kind: ServiceAccount
    name: otel-agent-opentelemetry-collector
    namespace: otel-agent

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-gateway-opentelemetry-collector
  namespace: otel-gateway
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: opamp-fleet

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-server
  namespace: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: opamp-fleet

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-server-role
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: opamp-fleet
rules:
  - apiGroups: [""]
    resources: ["endpoints", "services"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-server-binding
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: opamp-fleet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-server-role
subjects:
  - kind: ServiceAccount
    name: prometheus-server
    namespace: prometheus
